# Generated by Django 4.2.4 on 2023-11-30 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro_history', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_text',
            new_name='project_name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_auth',
            new_name='project_operator',
        ),
    ]
