# Generated by Django 4.2.4 on 2023-12-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_history', '0002_rename_project_text_project_project_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_date',
            field=models.DateTimeField(max_length=200),
        ),
    ]
